name: CasaXaver
favicon: null
layout_spectrum: 0.5717
typography_spectrum: 0.54141
title: 'A Luxury Garden Escape in Mérida, Yucatán, Mexico'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6dfffe'
    - '#40b3fc'
    - '#2573fa'
    - '#a3a9b6'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
