name: CasaXaver
favicon: null
layout_spectrum: 0.3855749301146716
typography_spectrum: 0.8533445154316723
title: A Luxury Garden Escape in Mérida YUC Mexico
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.05263815191574395
  lightness: 0.9013995053246617
  saturation: 0.25492903823032975
  rhythmicContrast: 0.5614438438788056
purpose: []
