name: CasaXaver
favicon: null
layout_spectrum: 0.5717
typography_spectrum: 0.54141
title: 'A Luxury Garden Escape in Mérida, Yucatán, Mexico'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4d8c2'
    - '#55b5d8'
    - '#7d6b39'
    - '#0071b7'
    - '#141100'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
