name: CasaXaver
favicon: null
layout_spectrum: 0.23953
typography_spectrum: 0.54141
title: 'A Luxury Garden Escape in Mérida, Yucatán, Mexico'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8ab2ba'
    - '#b03816'
    - '#e79d79'
    - '#762000'
    - '#6e4a09'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
